<a href="https://colab.research.google.com/github/sumana-vemuri/ADATA690-WANG/blob/master/assignments/pandas_aggregate.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import string


In [2]:
x=range(5)
type(x)

range

In [3]:
list(x)

[0, 1, 2, 3, 4]

In [4]:
y=np.arange(5)
type(y)

numpy.ndarray

In [5]:
list(y)

[0, 1, 2, 3, 4]

In [6]:
#builder pattern 
a=np.arange(100)
print(a)
#one dimenstion 
a
#2D
b=a.reshape(10,10)
b
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [7]:
string.ascii_uppercase

'ABCDEFGHIJKLMNOPQRSTUVWXYZ'

In [8]:
x=np.arange(100).reshape(10,10)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [9]:
y=list(string.ascii_uppercase)[0:10]
y

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [10]:
df=pd.DataFrame(x, columns=y)
df

A   B   C   D   E   F   G   H   I   J
0   0   1   2   3   4   5   6   7   8   9
1  10  11  12  13  14  15  16  17  18  19
2  20  21  22  23  24  25  26  27  28  29
3  30  31  32  33  34  35  36  37  38  39
4  40  41  42  43  44  45  46  47  48  49
5  50  51  52  53  54  55  56  57  58  59
6  60  61  62  63  64  65  66  67  68  69
7  70  71  72  73  74  75  76  77  78  79
8  80  81  82  83  84  85  86  87  88  89
9  90  91  92  93  94  95  96  97  98  99

In [11]:
df.dtypes
df.info()
df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 10 columns):
A    10 non-null int32
B    10 non-null int32
C    10 non-null int32
D    10 non-null int32
E    10 non-null int32
F    10 non-null int32
G    10 non-null int32
H    10 non-null int32
I    10 non-null int32
J    10 non-null int32
dtypes: int32(10)
memory usage: 528.0 bytes


(10, 10)

In [12]:
#to produce summary statistics
df.describe()

A          B          C          D          E          F  \
count  10.000000  10.000000  10.000000  10.000000  10.000000  10.000000   
mean   45.000000  46.000000  47.000000  48.000000  49.000000  50.000000   
std    30.276504  30.276504  30.276504  30.276504  30.276504  30.276504   
min     0.000000   1.000000   2.000000   3.000000   4.000000   5.000000   
25%    22.500000  23.500000  24.500000  25.500000  26.500000  27.500000   
50%    45.000000  46.000000  47.000000  48.000000  49.000000  50.000000   
75%    67.500000  68.500000  69.500000  70.500000  71.500000  72.500000   
max    90.000000  91.000000  92.000000  93.000000  94.000000  95.000000   

               G          H          I          J  
count  10.000000  10.000000  10.000000  10.000000  
mean   51.000000  52.000000  53.000000  54.000000  
std    30.276504  30.276504  30.276504  30.276504  
min     6.000000   7.000000   8.000000   9.000000  
25%    28.500000  29.500000  30.500000  31.500000  
50%    51.000000  52.000000  53.000000  54.000000  
75%    73.500000  74.500000  75.500000  76.500000  
max    96.000000  97.000000  98.000000  99.000000

In [13]:
#the summary statistics does not produce the sum od each column or row
#we use aggregate function 
#default-- aggregate of rows
df.aggregate("sum")

A    450
B    460
C    470
D    480
E    490
F    500
G    510
H    520
I    530
J    540
dtype: int64

In [14]:
df.agg("sum", axis="columns")

0     45
1    145
2    245
3    345
4    445
5    545
6    645
7    745
8    845
9    945
dtype: int64

In [15]:
df.agg(['sum','median','std'])

A           B           C           D           E  \
sum     450.000000  460.000000  470.000000  480.000000  490.000000   
median   45.000000   46.000000   47.000000   48.000000   49.000000   
std      30.276504   30.276504   30.276504   30.276504   30.276504   

                 F           G           H           I           J  
sum     500.000000  510.000000  520.000000  530.000000  540.000000  
median   50.000000   51.000000   52.000000   53.000000   54.000000  
std      30.276504   30.276504   30.276504   30.276504   30.276504

In [16]:
df=pd.DataFrame([[1,2,3],[4,5,6],[7,8,9],[np.nan,np.nan,np.nan]],columns=["A","B","C"])
df

A    B    C
0  1.0  2.0  3.0
1  4.0  5.0  6.0
2  7.0  8.0  9.0
3  NaN  NaN  NaN

In [17]:
df.describe()

A    B    C
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

In [18]:
df.agg("min", axis="columns")

0    1.0
1    4.0
2    7.0
3    NaN
dtype: float64

In [25]:
x=np.random.randint(0,100,100).reshape(20,5)
x

array([[17, 80, 12, 42, 56],
       [47, 50, 66, 78, 26],
       [84, 57, 35, 18, 49],
       [57, 84, 41, 71, 43],
       [28, 97, 65, 82, 48],
       [ 8, 31,  7, 26, 72],
       [93, 14,  3, 32, 67],
       [64,  4, 14, 71, 77],
       [ 6,  6, 80, 43, 97],
       [51, 95, 71, 24, 63],
       [49, 30, 68, 76, 46],
       [ 3,  8, 30, 83, 64],
       [82, 48, 10, 66, 49],
       [11, 53, 19, 27, 83],
       [12, 86, 49, 25, 91],
       [19, 52, 94, 19, 42],
       [11, 26, 65,  8, 10],
       [87, 20, 88, 88, 27],
       [64, 11, 99, 47,  4],
       [21, 14, 67, 59, 90]])

In [26]:
y=string.ascii_uppercase
y

'ABCDEFGHIJKLMNOPQRSTUVWXYZ'

In [27]:
y=list(y)[0:5]
y

['A', 'B', 'C', 'D', 'E']

In [28]:
df = pd.DataFrame(x,columns=y)
df

A   B   C   D   E
0   17  80  12  42  56
1   47  50  66  78  26
2   84  57  35  18  49
3   57  84  41  71  43
4   28  97  65  82  48
5    8  31   7  26  72
6   93  14   3  32  67
7   64   4  14  71  77
8    6   6  80  43  97
9   51  95  71  24  63
10  49  30  68  76  46
11   3   8  30  83  64
12  82  48  10  66  49
13  11  53  19  27  83
14  12  86  49  25  91
15  19  52  94  19  42
16  11  26  65   8  10
17  87  20  88  88  27
18  64  11  99  47   4
19  21  14  67  59  90

In [29]:
df.describe()

A          B         C          D          E
count  20.00000  20.000000  20.00000  20.000000  20.000000
mean   40.70000  43.300000  49.15000  49.250000  55.200000
std    30.68533  31.556299  31.19763  25.981522  26.053791
min     3.00000   4.000000   3.00000   8.000000   4.000000
25%    11.75000  14.000000  17.75000  25.750000  42.750000
50%    37.50000  39.500000  57.00000  45.000000  52.500000
75%    64.00000  62.750000  68.75000  72.250000  73.250000
max    93.00000  97.000000  99.00000  88.000000  97.000000

In [30]:
df.aggregate("sum")

A     814
B     866
C     983
D     985
E    1104
dtype: int64

In [32]:
df.agg(['sum','median','std',"min",'max'])

A           B          C           D            E
sum     814.00000  866.000000  983.00000  985.000000  1104.000000
median   37.50000   39.500000   57.00000   45.000000    52.500000
std      30.68533   31.556299   31.19763   25.981522    26.053791
min       3.00000    4.000000    3.00000    8.000000     4.000000
max      93.00000   97.000000   99.00000   88.000000    97.000000